### ISSUE TITLE
Google Play Games

### ISSUE THREAD

**Issue by GeitHub** [microg/android_packages_apps_FakeStore#11]
Hey, not sure where else to put this issue.

I was wondering if it's ever been attempted to make a FakeGames package that does the same for Google Play Games? Many high profile titles don't allow you to play them without having Google Play Games installed (Call Of Duty Black Ops Zombies for example). 

I found this issue:
https://github.com/microg/android_packages_apps_GmsCore/issues/163

but it talks about recreating functionality, where this would be a simple signature spoof, but perhaps it has already been attempted?

Def interested in taking a crack at it on my winter break if it hasn't been shown not to work.

**Comment by ale5000-git** [comment]
You misunderstood the issue, what is requested [here](https://github.com/microg/android_packages_apps_GmsCore/issues/163) is to add the missing APIs inside microG GmsCore (the ones used by Google Play Games) so that the official apk can work correctly.

**Comment by ale5000-git** [comment]
@GeitHub: Apparently what you are asking already exist [here](http://repo.xposed.info/module/com.fifsource.android.noplaygames).

**Comment by ShapeShifter499** [comment]
@ale5000-git I came here looking for the same thing but I'm on Nougat LineageOS 14.1.  Any solutions for Nougat that would be similar to that XPosed module?

**Comment by ale5000-git** [comment]
@ShapeShifter499: Sorry for the late reply but I don't know any alternative.
