### ISSUE TITLE
How to start GrantFakeSignaturePermissionActivity ?

### ISSUE THREAD

**Issue by ghost** [microg/android_packages_apps_FakeStore#12]
Hi
i patched the signature spoofing file to my build but i couldnt find a way to start GrantFakeSignaturePermissionActivity from within Android interface.
Android 7.1.1

greetings

**Comment by mar-v-in** [comment]
If you have a launcher that is able to do so, you might be able to launch in the Activity, but it's not intended to be used that way. The idea is that a future version of GmsCore provides the possibility to invoke it.

If you want to grant the permission, you can still do it through the system settings -> Apps -> Gear icon -> App permissions -> Spoof package signatures

**Comment by ghost** [comment]
thank you for your quick answer!
this didnt work for me, only apps that asked at least once for that permission are listed there
i found a way:
`adb shell am start com.android.vending/.GrantFakeSignaturePermissionActivity`
after that command the Fakestore is listed next to gmscore in the menu you described.

**Comment by IzzySoft** [comment]
@mar-v-in 

> If you want to grant the permission, you can still do it through the system settings -> Apps -> Gear icon -> App permissions -> Spoof package signatures

I've tried that, but FakeStore isn't listed there (microG Services Core is, however, and has it granted). Tried

    adb shell am start com.android.vending/.GrantFakeSignaturePermissionActivity

as pointed out by @Herny64, but got an error back:

    Error: Activity class {com.android.vending/com.android.vending.GrantFakeSignaturePermissionActivity} does not exist.

FakeStore was downloaded here from the `releases/` page. Checking again, it seems I didn't pick the latest version (v0.0.2) as it has no APK attached. Could that be the reason? So where to pick the latest version then? Could you please attach it here (or at least point to where it can be found)? Even the link from the [microG download page](https://microg.org/download.html) just points here to the Github releases page.

AFAIR, FakeStore must be installed as system app (at least that was the case with BlankStore) – so it doesn't help much that one can install it via your F-Droid repo :wink:

**Comment by mar-v-in** [comment]
FakeStore only needs to be a system app if signature spoofing is restricted to system apps. I just uploaded the 0.0.2 release to GitHub, so you can download it from there.

The microG download page requires JavaScript to allow you to download the latest release directly (the website is basically a client to the microG F-Droid repo), it will fallback to GitHub if you have JS disabled.

**Comment by IzzySoft** [comment]
Thanks for the fast response, @mar-v-in ! Indeed I had JavaScript disabled. Downloaded v0.0.2, installed it as system app (`/system/priv-app/FakeStore/FakeStore.apk`), rebooted (yikes! Fixed permissions on `/system/priv-app/FakeStore` and rebooted again) – and what shall I say? After enabling system apps, FakeStore turns up and I can grant it the permission. Thanks a lot!

Short question in this context (as I'm asked every now and then): BlankStore is considered dead (at least on MM and above – on me it was crashing whenever I tried to list something), right? Or do you plan to fix it again? Or is another replacement making progress? Of course there's YalpStore which can be used together with FakeStore (the former for installs/updates, the latter to "satisfy apps" requiring the presence of Playstore) …

**Comment by mar-v-in** [comment]
Yes, with YalpStore, there is no need to maintain the legacy BlankStore.

**Comment by IzzySoft** [comment]
OK, got it. We've got enough other tasks at hand, so better focus wherever possible :wink: Though of course it had a special appeal (to complement microG). Later then, maybe – indeed not that urgent, with that combination being available.

Thanks again! Really love microG :innocent:

**Comment by ghost** [comment]
> Downloaded v0.0.2, installed it as system app (/system/priv-app/YalpStore/YalpStore.apk), rebooted (yikes! Fixed permissions on /system/priv-app/YalpStore and rebooted again) 

@IzzySoft do you mean BlankStore ? or is yalpstore integrated in microG ?

**Comment by IzzySoft** [comment]
Urgs, got me, @Herny64 – typo. I of course meant FakeStore. Fixed the post. And no, YalpStore is a separate app and not part of µG – but I use it for the few cases I need to update stuff from "the walled garden" (e.g. TiBu).
