### ISSUE TITLE
Integrating FakeStore in AOSP

### ISSUE THREAD

**Issue by mikalackis** [microg/android_packages_apps_FakeStore#15]
I tried to integrate FakeStore in a pure AOSP rom i'm working on. I checked out the source so the APK gets build properly and its places in system image.

It seems that in this case I cant grant the fake signature permission to fake store since it is not available in Settings -> Apps -> Permissions. On the other hand, if I install the FakeStore apk directly, without embedding it in my ROM, the app is listed in apps that require signature spoofing. Anyone encountered this problem?

**Comment by iRave** [comment]
@Herny64 's comment at #12 fixes this issue for me.
execute with your phone connected:
>  adb shell am start com.android.vending/.GrantFakeSignaturePermissionActivity
