### ISSUE TITLE
Google apps ask to update Play Store

### ISSUE THREAD

**Issue by ildar** [microg/android_packages_apps_FakeStore#19]
How to fix that / make them work?

P.S. a chat / IRC / gittim would be excellent for community.

**Comment by ildar** [comment]
That's probably GmsCore problem, right?

**Comment by rugk** [comment]
Yes, the version number just needs to be increased. That is easy though, but wrong repo here. :smile:

**Comment by ale5000-git** [comment]
This problem doesn't belong to this repo.
