### ISSUE TITLE
Incompatible with OneDrive 6.16? - how to downgrade

### ISSUE THREAD

**Issue by pbiering** [microg/android_packages_apps_FakeStore#24]
Hi,

I've "accidently" upgraded on LOS 17.1 MicroG from 0.0.2 to 0.1.0 - all working fine but previously installed Microsoft OneDrive app is now crashing instantly after start - I wanted to test with 0.0.2 again, but can't downgrade with F-Droid ("Error -25: The new package has an older version code than the currently installed package)

Is there any hint available how to downgrade FakeStore back to 0.0.2 - thank you very much!

(and keep on the good work!!!)

**Comment by JonnyTech** [comment]
Remove (uninstall) newer version then install older one. But first can you provide logs to help diagnose the problem?

**Comment by pbiering** [comment]
Thank you for your fast response. F-Droid and Settings are not allowing to deinstall. Is there any FAQ available how I can retrieve the logs and potential location?

**Comment by JonnyTech** [comment]
I was able to uninstall and reinstall with fdroid:

![img_0](https://user-images.githubusercontent.com/3584732/97703108-f5c32680-1aa7-11eb-833a-798f8b091efa.jpg)
![img_1](https://user-images.githubusercontent.com/3584732/97703119-f9ef4400-1aa7-11eb-892c-57b5e7d3fbac.jpg)

I could also uninstall from system app settings:

![img_2](https://user-images.githubusercontent.com/3584732/97703555-b8ab6400-1aa8-11eb-9816-786a20520eb4.jpg)

Maybe find the actual install folder and remove it, mine is `/data/app/com.android.vending-KH1FnZGaKRIcpiXloYIj_Q==`.

For logs, just grab any logcat app and send what happens when onedrive starts.

**Comment by pbiering** [comment]
Thank you for the logcat hint, here I found an exception once OneDrive is starting:

```
10-27 08:35:46.897 10353 10405 E AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
10-27 08:35:46.897 10353 10405 E AndroidRuntime: Process: com.microsoft.skydrive, PID: 10353
10-27 08:35:46.897 10353 10405 E AndroidRuntime: java.lang.IllegalStateException: A fatal developer error has occurred. Class name: zzf. Start service action: com.google.firebase.auth.api.gms.service.START. Service Descriptor: com.google.firebase.auth.api.internal.IFirebaseAuthService.
10-27 08:35:46.897 10353 10405 E AndroidRuntime:        at com.google.android.gms.common.internal.BaseGmsClient$a.zza(SourceFile:13)
10-27 08:35:46.897 10353 10405 E AndroidRuntime:        at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(SourceFile:6)
10-27 08:35:46.897 10353 10405 E AndroidRuntime:        at com.google.android.gms.common.internal.BaseGmsClient$b.handleMessage(SourceFile:35)
10-27 08:35:46.897 10353 10405 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
10-27 08:35:46.897 10353 10405 E AndroidRuntime:        at com.google.android.gms.internal.common.zze.dispatchMessage(SourceFile:1)
10-27 08:35:46.897 10353 10405 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
10-27 08:35:46.897 10353 10405 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
10-27 08:35:58.724 10502 10555 E AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
```

**Comment by pbiering** [comment]
can't access the "/data" folder with "adb shell" as permissions are not allowing "ls-al" (directory has 771 system:system while user is "shell". but downgraded "somehow" using
```
adb uninstall com.android.vending
```
0.0.2 is now displayed in F-Droid - but OneDrive is still crashing

```
10-31 08:10:03.798  5773  5790 I ActivityTaskManager: START u0 {flg=0x4000000 cmp=com.microsoft.skydrive/.fre.OnboardingExperienceActivity (has extras)} from uid 10220
10-31 08:10:03.812  7015  7042 D GmsFirebaseAuth: bound by: GetServiceRequest{serviceId=FIREBASE_AUTH, gmsVersion=12451000, packageName='com.microsoft.skydrive', extras=Bundle[{com.google.firebase.auth.API_KEY=AIza***}]}
10-31 08:10:03.813 11886 11938 E AndroidRuntime: FATAL EXCEPTION: GoogleApiHandler
10-31 08:10:03.813 11886 11938 E AndroidRuntime: Process: com.microsoft.skydrive, PID: 11886
10-31 08:10:03.813 11886 11938 E AndroidRuntime: java.lang.IllegalStateException: A fatal developer error has occurred. Class name: zzf. Start service action: com.google.firebase.auth.api.gms.service.START. Service Descriptor: com.google.firebase.auth.api.internal.IFirebaseAuthService. 
10-31 08:10:03.813 11886 11938 E AndroidRuntime: 	at com.google.android.gms.common.internal.BaseGmsClient$a.zza(SourceFile:13)
10-31 08:10:03.813 11886 11938 E AndroidRuntime: 	at com.google.android.gms.common.internal.BaseGmsClient$zzc.zzo(SourceFile:6)
10-31 08:10:03.813 11886 11938 E AndroidRuntime: 	at com.google.android.gms.common.internal.BaseGmsClient$b.handleMessage(SourceFile:35)
10-31 08:10:03.813 11886 11938 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-31 08:10:03.813 11886 11938 E AndroidRuntime: 	at com.google.android.gms.internal.common.zze.dispatchMessage(SourceFile:1)
10-31 08:10:03.813 11886 11938 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
10-31 08:10:03.813 11886 11938 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
```

It worked days before - hopefully one can lead me where to deeper look to get it back running again

**Comment by JonnyTech** [comment]
Did you reboot after downgrading?

**Comment by pbiering** [comment]
Downgraded, rebooted, OneDrive reinstalled, no luck
Deinstalled Reinstalled 0.0.2 via "adb install" (which looks like resulting in an overlay), reboot, Install, no luck
Deinstalled 0.0.2 "overlay", reboot, deinstalled OneDrive, reboot, installed OneDrive , same issue again (even reinstalled Aurora Store because suddenly it was also not able to upgrade existing apps anymore).

More hints are welcome.

**Comment by JonnyTech** [comment]
Sounds like you have a system-wide problem with permissions if aurora store is having problems too. Try resetting global app preferences: `settings >> apps >> all apps >> menu bar >> reset app preferences`. You may have to grant specific permissions again after a reboot.

Have you tried downgrading the onedrive app? A recent update may be the underlying issue.

**Comment by pbiering** [comment]
Thank you for still taking care!

Permissions resetted, OneDrive 14.2 APK installed, same issue, same exception - it's the only app which broke, others are working fine - any other idea beside a factory reset (which I don't like to execute at the moment...).

**Comment by JonnyTech** [comment]
Which version of gmscore are you using? (https://github.com/microg/android_packages_apps_GmsCore/releases)

The latest (v0.2.13.203915) added: Partial support for Firebase Authentication

Maybe that is the fault. Previous versions failed with firebase and used fallback methods.

Because your logs show firebase exceptions then fakestore may not be to blame. Remove gmscore and try an older version.

Maybe raise an issue in the main gmscore tracker.

**Comment by pbiering** [comment]
@JonnyTech: great hint (you saved my day) - that was the issue...now I can remember that I did beside updating FakeStore also the update of GmsCore to satisfy the German Corona Warning App... - downgraded GmsCore to GmsCore-v0.2.12.203315.apk and OneDrive is working fine after reporting an issue with Google Playstore (don't care about...) - will close this ticket and open a new one to GmsCore.
