### ISSUE TITLE
See my apps, but the status is "installed" (LOS 17.1 with integrated fakestore)

### ISSUE THREAD

**Issue by schdrag** [microg/android_packages_apps_FakeStore#25]
Can't install apps from the playstore. I succeed to login, see "my apps", but the status is wrong: I had installed these apps (on another android), so I should be able to install these apps again on the clean install.
I have the  Pre-installed microG build variant with additional security patches from https://forum.xda-developers.com/t/rom-unofficial-10-0-signed-ota-lineage-os-17-1-for-xperia-z1-compact.4007983/
The google login is not stored at all, might be intended.
self check test of microg ist perfect!

**Comment by ildar** [comment]
I think you misunderstand this app. It is Fake store. If you need to
install/uninstall something, use e.g. Aurora Store (
https://gitlab.com/AuroraOSS/AuroraStore/), you can download it from
F-Droid.

**Comment by ale5000-git** [comment]
How already said Fake Store is just a dummy application, it doesn't do anything and cannot be executed.
It have to be installed because otherwise apps will nag about missing Google Play Services, but to install apps you have to use another store like Aurora Store or F-Droid.
