### ISSUE TITLE
Change app version to match with Google Play Store

### ISSUE THREAD

**Issue by Rexadev** [microg/android_packages_apps_FakeStore#27]
FakeStore App version is 0.75 but Google Play Store is v27.***** maybe it detects that.

Change App version in manifest but show true microG version in settings.
Still bump it up to prevent fingerprinting

**Comment by Rexadev** [comment]
Bump

**Comment by mar-v-in** [comment]
So far, I'm not aware of any issue arising from FakeStore not having a version that matches Play Store. Maintaining the version code means additional maintenance work and makes updating a more tedious process, thus if not needed, I prefer not going that route.

**Comment by ildar** [comment]
@Rexadev , you probably have a problem elsewhere.

**Comment by Rexadev** [comment]
> So far, I'm not aware of any issue arising from FakeStore not having a version that matches Play Store. Maintaining the version code means additional maintenance work and makes updating a more tedious process, thus if not needed, I prefer not going that route.

Change App version in manifest but show true microG version in settings.
Still bump it up to prevent fingerprinting

**Comment by ale5000-git** [comment]
@Rexadev
The issue has been fixed here: https://github.com/microg/FakeStore/issues/43
