### ISSUE TITLE
Why is v0.1.0 (latest on GitHub) shown as a preview release on the microG wesite and F-Droid repository?

### ISSUE THREAD

**Issue by FintasticMan** [microg/android_packages_apps_FakeStore#28]
Like the title says, [v0.1.0](https://github.com/microg/FakeStore/releases/tag/v0.1.0) is shown on the microG download page as a "preview release". On F-Droid the release isn't marked as "suggested". 
Why is that? Is the release buggy?

**Comment by mar-v-in** [comment]
Version 0.2.0 is now the suggested on both website and F-Droid.
