### ISSUE TITLE
[<package-id>] <Where is the app install>

### ISSUE THREAD

**Issue by Zawo1995** [microg/android_packages_apps_FakeStore#29]
Well,where is the app install?
Today I update the mobile system ,and i couldnot find the app in [mobile's setting/installed apps], now I want to try to delete in filesystem.

**Comment by tiziodcaio** [comment]
The app has not the purpose to replace play store. Use aurora store instead

**Comment by tiziodcaio** [comment]
It must be searched as google play store as it has signature spoofing, so is com.android.vending or similar i dont remember

**Comment by ale5000-git** [comment]
The question is unclear and I think he/she has already fixed the problem by now.
If not the case please write it.
