### ISSUE TITLE
not able to compile it

### ISSUE THREAD

**Issue by zoff99** [microg/android_packages_apps_FakeStore#3]
can you give more details how to compile this?
i am using BlankStore for now (which is also almost impossible to compile)

or is there a binary repository to download the apk from?

**Comment by pejakm** [comment]
> or is there a binary repository to download the apk from?

https://github.com/microg/android_packages_apps_FakeStore/releases

**Comment by relyt29** [comment]
I added instructions on how to compile the application
https://github.com/microg/android_packages_apps_FakeStore/wiki/Building
