### ISSUE TITLE
Fake Store v 0.1.0 not visible in launcher

### ISSUE THREAD

**Issue by Sawiq** [microg/android_packages_apps_FakeStore#31]
**Describe the bug**
Fake Store is not displayed in apps list. When searched in System/Application there is no button to open the app either.

**To Reproduce**
1. Download *.apk file
2. `adb root`
3. `adb remount`
2. `adb push com.android.vending-22.apk /system/priv-app/`
3. `adb shell chmod 644 /system/priv-app/*.apk`
4. `adb reboot`
5. Search for Play Store in launcher / App drawer

**Expected behavior**
Fake store icon visible.

**Screenshots**

**System**
Android Version: 11
Custom ROM: [AOSP 11](https://forum.xda-developers.com/t/rom-11-darkjoker360-aosp-11-for-huawei-p8-lite-2017.4220705/)

**Additional context**
Had to install as system app, otherwise it did not get package signature spoofing permission. The app was visible if installed via F-Droid as user app.

**Comment by ildar** [comment]
FakeStore is made for different purposes. Use Aurora Store or alike. Get
more help in chat.

**Comment by waltercool** [comment]
> The app was visible if installed via F-Droid as user app.

It never been, fake store is made to replace a missing Google Play Store and add the intents needed for certain apps to avoid crashes. That's all.

It's not a real application.

**Comment by ale5000-git** [comment]
How already said Fake Store is just a dummy application, it doesn't do anything and cannot be executed.
It have to be installed because otherwise apps will nag about missing Google Play Services.
