### ISSUE TITLE
Bump targetSdk

### ISSUE THREAD

**Issue by SkewedZeppelin** [microg/android_packages_apps_FakeStore#42]
targetSdk is currently 24, please bump to 29 if possible to match GmsCore

ref: https://github.com/Divested-Mobile/DivestOS-Build/commit/b7d37053c32cdcaf6cf2ee371977e8dac1f6be8c

edit: silly me should've checked pulls first: https://github.com/microg/FakeStore/pull/41

**Comment by ale5000-git** [comment]
@SkewedZeppelin
It is now at 29 => https://github.com/microg/FakeStore/commit/0498ef775584f1c8f6b0e5d183e3d3b06fc81ed4
