### ISSUE TITLE
Play Store required version too low

### ISSUE THREAD

**Issue by TinfoilSubmarine** [microg/android_packages_apps_FakeStore#43]
**Describe the bug**
When walking through setting up a work profile with Intune Company Portal, it checks the version of Play Store and sees that the version code is too low (currently 30) compared to the required version (80711100).

**To Reproduce**
1. Install Intune Company Portal
2. Walk through setting up
3. Intune Company Portal will check if required version of Play Store is installed

**Expected behavior**
FakeStore should have a version number / versionCode that makes it more realistically appear as the real Play Store.

**System**
Android Version: 13
Custom ROM: LineageOS 20

**Comment by mar-v-in** [comment]
Fixed via 087436d9aae23bedb0ecf6eb53d82f8be2c6f7f0

**Comment by ale5000-git** [comment]
For those interested to test it, there is a new build signed by me here: https://github.com/micro5k/microg-unofficial-installer/raw/main/zip-content/origin/priv-app/FakeStore.apk
