### ISSUE TITLE
[com.lingodeer] LingoDeer crashes at start - "Something went wrong"

### ISSUE THREAD

**Issue by ueco-jb** [microg/android_packages_apps_FakeStore#47]
**Affected app**
Name: LingoDeer
Package id: com.lingodeer
https://play.google.com/store/apps/details?id=com.lingodeer&gl=US

**Describe the bug**
Couple seconds after starting the app popup "Something went wrong" shows up with communicate to check if latest Google Play Store version is installed. App used to work, after one of recent updates it stopped.

**To Reproduce**
1. Install app and run it.

**Expected behavior**
After couple seconds "Something went wrong" popup should appear.

**Screenshots**
![Screenshot_20221114-140842_Trebuchet](https://user-images.githubusercontent.com/88148473/201671790-1597672b-0dc0-4bd0-9d1b-3ec7092e23f2.png)

**System**
Android Version: 12
Custom ROM: lineage-19.1-20221023-microG-sake

**microG**
microG Core version: 0.2.25.223616-8 (2a19ef4) - latest nightly
microG Self-Check results: All ticked
![Screenshot_20221114-142347_Trebuchet](https://user-images.githubusercontent.com/88148473/201671810-654021d5-8e80-42fd-a9d9-14d7529c9f7c.png)

**Comment by ale5000-git** [comment]
Could you please post a logcat?

**Comment by ueco-jb** [comment]
@ale5000-git 
[lingodeer_logcat.log](https://github.com/microg/GmsCore/files/10006046/lingodeer_logcat.log)

Seems like it can't connect to licensing server?
```
LicenseClientV3: Retry microg/GmsCore#3. License check failed with error 'Could not bind with the licensing service'. Next try in 1s
QCNEJ/WlanStaInfoRelay: Received action: android.net.wifi.RSSI_CHANGED
IncomingMessageObserver: Application level read timeout...
IncomingMessageObserver: Network: true, Foreground: false, FCM: false, Stay open requests: [], Censored: false, Registered: true, Proxy: false, Force websocket: false
IncomingMessageObserver: Reading message...
LicenseClientV3: Connecting to the licensing service...
ActivityManager: Unable to start service Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending } U=0: not found
LicenseClientV3: Error while checking license: com.pairip.licensecheck3.LicenseClientV3$LicenseCheckException: Could not bind with the licensing service
LicenseClientV3: 	at com.pairip.licensecheck3.LicenseClientV3.connectToLicensingService(LicenseClientV3.java:100)
LicenseClientV3: 	at com.pairip.licensecheck3.LicenseClientV3.$r8$lambda$mdXeWrbXjkADjcVRgNH0zKMqAIU(Unknown Source:0)
LicenseClientV3: 	at com.pairip.licensecheck3.LicenseClientV3$$ExternalSyntheticLambda3.run(Unknown Source:2)
LicenseClientV3: 	at android.os.Handler.handleCallback(Handler.java:938)
LicenseClientV3: 	at android.os.Handler.dispatchMessage(Handler.java:99)
LicenseClientV3: 	at android.os.Looper.loopOnce(Looper.java:201)
LicenseClientV3: 	at android.os.Looper.loop(Looper.java:288)
LicenseClientV3: 	at android.app.ActivityThread.main(ActivityThread.java:7870)
LicenseClientV3: 	at java.lang.reflect.Method.invoke(Native Method)
LicenseClientV3: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
LicenseClientV3: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10176; state: ENABLED
ThermalEngine: thermal_sensor_get_temperature: virtual-therm Reading 22937 .
android.hardware.thermal@2.0-service.qti: uevent triggered for sensor: camera-therm-usr
WindowManager: Attempted to add application window with unknown token Token{9ab8f6a ActivityRecord{a717ad4 u0 com.lingodeer/com.lingo.lingoskill.ui.base.SplashActivity t-1 f}}}.  Aborting.
```

**Comment by pelag0s** [comment]
Probably the same problem with LockMyPix (https://play.google.com/store/apps/details?id=com.fourchars.lmpfree) over here.

A few seconds after startup, the exact same window appears and closes the app afterwards.

The app has been working correctly a few months before. (But might also be related to the Android 13 update of CalyxOS?)

**System**
Android Version: 13
Custom ROM: CalyxOS 4.4.0

**microG**
microG Core version: 0.2.26.223616-37 (23ae934) 
microG Self-Check results: All ticked

**Logcat output:**

```
D LicenseClientV3: Retry microg/GmsCore#3. License check failed with error 'Could not bind with the licensing service'. Next try in 1s                                                                                             
I Ads     : Please set theme of AdActivity to @android:style/Theme.Translucent to enable transparent background interstitial ad.
D GmsDummySvc: bound by: GetServiceRequest{serviceId=ADREQUEST, gmsVersion=12451000, packageName='com.fourchars.lmpfree', extras=Bundle[{}]}
I Ads     : SDK version: afma-sdk-a-v223104000.223104000.0
I Ads     : HTTP timeout: 60000 milliseconds.
D LicenseClientV3: Connecting to the licensing service...
W ActivityManager: Unable to start service Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending } U=0: not found
E LicenseClientV3: Error while checking license: com.pairip.licensecheck3.LicenseClientV3$LicenseCheckException: Could not bind with the licensing service
E LicenseClientV3:       at com.pairip.licensecheck3.LicenseClientV3.connectToLicensingService(LicenseClientV3.java:100)
E LicenseClientV3:       at com.pairip.licensecheck3.LicenseClientV3.$r8$lambda$mdXeWrbXjkADjcVRgNH0zKMqAIU(Unknown Source:0)
E LicenseClientV3:       at com.pairip.licensecheck3.LicenseClientV3$$ExternalSyntheticLambda3.run(Unknown Source:2)
E LicenseClientV3:       at android.os.Handler.handleCallback(Handler.java:942)
E LicenseClientV3:       at android.os.Handler.dispatchMessage(Handler.java:99)
E LicenseClientV3:       at android.os.Looper.loopOnce(Looper.java:201)
E LicenseClientV3:       at android.os.Looper.loop(Looper.java:288)
E LicenseClientV3:       at android.app.ActivityThread.main(ActivityThread.java:7872)
E LicenseClientV3:       at java.lang.reflect.Method.invoke(Native Method)
E LicenseClientV3:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E LicenseClientV3:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by yennor** [comment]
If somebody searches for it:
Vivino has the exact same problem. Installing an older version of it works.
https://play.google.com/store/apps/details?id=vivino.web.app

**Comment by hillscott** [comment]
Seeing this same issue here with Planet Fitness Workouts 
[https://play.google.com/store/apps/details?id=com.planetfitness](https://play.google.com/store/apps/details?id=com.planetfitness)

Logcat output:

W ActivityManager: Unable to start service Intent { act=com.android.vending.licensing.ILicensingService pkg=com.android.vending } U=0: not found
E LicenseClientV3: Error while checking license: com.pairip.licensecheck3.LicenseClientV3$LicenseCheckException: Could not bind with the licensing service.
E LicenseClientV3: 	at com.pairip.licensecheck3.LicenseClientV3.connectToLicensingService(LicenseClientV3.java:107)
E LicenseClientV3: 	at com.pairip.licensecheck3.LicenseClientV3.$r8$lambda$mdXeWrbXjkADjcVRgNH0zKMqAIU(Unknown Source:0)
E LicenseClientV3: 	at com.pairip.licensecheck3.LicenseClientV3$$ExternalSyntheticLambda3.run(Unknown Source:2)
E LicenseClientV3: 	at android.os.Handler.handleCallback(Handler.java:942)
E LicenseClientV3: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E LicenseClientV3: 	at android.os.Looper.loopOnce(Looper.java:201)
E LicenseClientV3: 	at android.os.Looper.loop(Looper.java:288)
E LicenseClientV3: 	at android.app.ActivityThread.main(ActivityThread.java:7884)
E LicenseClientV3: 	at java.lang.reflect.Method.invoke(Native Method)
E LicenseClientV3: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E LicenseClientV3: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
D CoreBackPreview: Window{1e80eea u0 com.planetfitness/crc64c58d90dbc7155540.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@8ff2424, mPriority=0}

**Comment by ueco-jb** [comment]
@mar-v-in Hey, I noticed you are working on that project. Is there anyone who could look up into it? Thank.

**Comment by Uldiniad** [comment]
I can also reproduce the same crash with https://play.google.com/store/apps/details?id=com.sap.mdc.loblaw.nativ

**Comment by ale5000-git** [comment]
This should be already fixed, try the latest version please: https://github.com/microg/FakeStore/releases
