### ISSUE TITLE
What is FakeStore used for ?

### ISSUE THREAD

**Issue by breversa** [microg/android_packages_apps_FakeStore#6]
Hi,
I'm wondering in what case it is necessary to mock the Play Store ?

**Comment by mar-v-in** [comment]
Play services contains a check to require the existence of Play store. FakeStore allows you to pass this check.

**Comment by breversa** [comment]
I did not know about that. Thank you @mar-v-in !

Though it may be obvious for some people, why not add that simple answer to the main page ?
