### ISSUE TITLE
Couldn't install current build

### ISSUE THREAD

**Issue by daktak** [microg/android_packages_apps_FakeStore#9]
Cannot install platform packages to user storage!
Built from source, install fails

E/        : Couldn't opendir /data/data/com.android.vending: No such file or directory
W/PackageManager: com.android.internal.os.InstallerConnection$InstallerException: Failed to execute destroy_app_data [null, com.android.vending, 0, 3, 0]: -2
W/PackageManager: Package couldn't be installed in /data/app/com.android.vending-1
W/PackageManager: com.android.server.pm.PackageManagerException: Cannot install platform packages to user storage!
W/PackageManager: 	at com.android.server.pm.PackageManagerService.scanPackageDirtyLI(PackageManagerService.java:8218)
W/PackageManager: 	at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:8001)
W/PackageManager: 	at com.android.server.pm.PackageManagerService.scanPackageTracedLI(PackageManagerService.java:7978)
W/PackageManager: 	at com.android.server.pm.PackageManagerService.installNewPackageLIF(PackageManagerService.java:14237)
W/PackageManager: 	at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:15295)
W/PackageManager: 	at com.android.server.pm.PackageManagerService.installPackageTracedLI(PackageManagerService.java:14957)
W/PackageManager: 	at com.android.server.pm.PackageManagerService.-wrap26(PackageManagerService.java)
W/PackageManager: 	at com.android.server.pm.PackageManagerService$10.run(PackageManagerService.java:12448)
W/PackageManager: 	at android.os.Handler.handleCallback(Handler.java:751)
W/PackageManager: 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/PackageManager: 	at android.os.Looper.loop(Looper.java:154)
W/PackageManager: 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/PackageManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
E/        : Couldn't opendir /data/app/vmdl170765407.tmp: No such file or directory
D/FileContentProvider: applied batch in provider com.owncloud.android.providers.FileContentProvider@317020f
D/RefreshFolderOperation: Send broadcast com.owncloud.android.operations.RefreshFolderOperation.EVENT_SINGLE_FOLDER_SHARES_SYNCED

**Comment by daktak** [comment]
0.0.1 works,
On nougat 7.1

**Comment by mar-v-in** [comment]
You signed your build with the platform key (the key you used to build your system). It's not possible to install platform apps (= apps signed with platform key) as user app. Use a different signing key to solve the problem.

**Comment by daktak** [comment]
Ahh, I did have an issue when incorporating into a ROM also, so should have been same key? I will try again

**Comment by daktak** [comment]
Re-tried, and works in full build .
